### ISSUE TITLE
Missing parts & bionics not working

### ISSUE THREAD

**Issue by Killface1980** [Killface1980/RW_FacialStuff#45]
CheckForAddedOrMissingBodyParts?

**Comment by Killface1980** [comment]
update – no idea, the hediffs list and/or bodypart list seems to be empty?

**Comment by Killface1980** [comment]
Potential fix on disk, fixed added parts (might spawn null? test!), still no missing parts.

**Comment by Killface1980** [comment]
fixed in current build

**Comment by lgn169** [comment]
there is still missing parts in 1.0 version. There are no prostetic arm and no bionic arm.
